[tool.poetry]
name = "paita"
version = "0.1.3"
description = "paita - Python AI Textual Assistant"
authors = ["villekr <ville.karkkainen@outlook.com>"]
readme = "README.md"
license = "MIT"
keywords = ["python", "textual", "ai", "chat", "openai", "chatgpt", "aws", "bedrock"]

[tool.poetry.dependencies]
python = "^3.8.1"
boto3 = "^1.34.34"
textual = "^0.52.1"
loguru = "^0.7.2"
langchain = "^0.1.11"
#langchain = { path = "../forks/langchain/libs/langchain", develop = true }
#langchain-core = { path = "../forks/langchain/libs/core", develop = true }
#langchain-community = { path = "../forks/langchain/libs/community", develop = true }
#langchain = { path = "../langchain/libs/langchain", develop = true }
#langchain-core = { path = "../langchain/libs/core", develop = true }
#langchain-community = { path = "../langchain/libs/community", develop = true }

langchain-openai = "^0.0.8"
appdirs = "^1.4.4"
pydantic = "^2.6.1"
cache3 = "^0.4.3"
aiofiles = "^23.2.1"
pyperclip = "^1.8.2"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
isort = "^5.12.0"
black = "^23.11.0"
textual-dev = "^1.5.1"
# boto3-stubs = "^1.34.37"
# boto3-stubs-lite = { version = "^1.34.37", extras = ["essential"] }
pytest = "^8.0.0"
pytest-asyncio = "^0.23.5"
flake8-bugbear = "^24.2.6"
flake8-bandit = "^4.1.1"
pytest-cov = "^4.1.0"
mypy = "^1.9.0"
boto3-stubs = "^1.34.60"
appdirs-stubs = "^0.1.0"
types-aiofiles = "^23.2.0.20240311"

[project.scripts]
paita = "paita.tui.app:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[settings]
profile = "black"

[tool.isort]
profile = "black"

[tool.pytest]
addopts = "-ra -q"
testpaths = [
    "tests"
]

[tool.pytest.ini_options]
addopts = "--cov=./paita/ --cov-report term-missing"

#[tool.coverage.run]
#source = [
#    "paita/"
#]
#
#[tool.coverage.report]
#show_missing=true
